version: '3.7'
services:
  mysql:
    init: true
    build:
      context: ./mysql
      dockerfile: mysql.dockerfile
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - BACKUP_ENABLED
      - BACKUP_INTERVAL
      - MYSQL_ROOT_PASSWORD
      - MYSQL_WP_DATABASE
      - MYSQL_WP_PASS
      - MYSQL_WP_USER
      - S3_MYSQL_BUCKET

  wordpress:
    init: true
    build:
      context: ./wordpress
      dockerfile: wordpress.dockerfile
    ports:
      - '8888:80'
    depends_on:
      - mysql
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - BACKUP_ENABLED
      - BACKUP_INTERVAL
      - MYSQL_ROOT_PASSWORD
      - MYSQL_WP_DATABASE
      - MYSQL_WP_PASS
      - MYSQL_WP_USER
      - S3_WORDPRESS_BUCKET
      - WP_RELEASE_URL
volumes:
  www-data:
  db-data:
